apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ssh-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ssh-server
    spec:
      containers:
      - name: ssh-server
        image: slalwani97/openssh
        command: ["sh", "-c", "service ssh start && sleep 10000"]
        imagePullPolicy: Always
        ports:
          - containerPort: 22
      nodeSelector:
        kubernetes.io/hostname: k8s-worker-01

---
apiVersion: v1
kind: Service
metadata:
  name: ssh-server
spec:
  # type: NodePort
  selector:
    app: ssh-server
  ports:
  - port: 22
    targetPort: 22
    protocol: TCP
    name: ssh
