---
apiVersion: v1
kind: Pod
metadata:
  labels:
    test-iperf3: client
  name: iperf3-client
spec:
  containers:
  - name: iperf3-client
    image: slalwani97/iperf
    args:
      - -c
      - 10.244.2.4
  restartPolicy: OnFailure
  nodeSelector:
    kubernetes.io/hostname: k8s-worker-01
